import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="nav">
        <Link href="/" className="bg-blue-200 rounded px-4 py-2">
          Home
        </Link>
        <Link href="/auth" className="bg-cyan-200 rounded px-4 py-2">
          Login
        </Link>
        <Link href="/board" className="bg-gray-200 rounded px-4 py-2">
          board
        </Link>
        </div>
        {children}</body>
    </html>
  );
}
