import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Providers from '#components/Providers'
import SignButton from '#components/SignButton'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Providers>
      <div className="nav">
        <Link href="/" className="bg-blue-200 rounded px-4 py-2">
          Home
        </Link>
        <SignButton></SignButton>
        <Link href="/board" className="bg-gray-200 rounded px-4 py-2">
          board
        </Link>
      </div>
      {children}
    </Providers>
    </body>
    </html>
  )
}
